name: build-images
on:
  push:
    branches: [ lang-fix, main ]
    tags: [ 'v*' ]   # optional: build on version tags too

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      REG: ghcr.io/${{ github.repository_owner }}
    steps:
      - uses: actions/checkout@v4

      - name: Set vars
        run: echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & push backend
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          push: true
          tags: |
            ${{ env.REG }}/adventurelog-backend:myfix
            ${{ env.REG }}/adventurelog-backend:myfix-${{ github.run_number }}
            ${{ env.REG }}/adventurelog-backend:myfix-${{ env.SHORT_SHA }}
            ${{ startsWith(github.ref, 'refs/tags/') && format('{0}/adventurelog-backend:{1}', env.REG, github.ref_name) || '' }}

      - name: Build & push frontend
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          push: true
          tags: |
            ${{ env.REG }}/adventurelog-frontend:myfix
            ${{ env.REG }}/adventurelog-frontend:myfix-${{ github.run_number }}
            ${{ env.REG }}/adventurelog-frontend:myfix-${{ env.SHORT_SHA }}
            ${{ startsWith(github.ref, 'refs/tags/') && format('{0}/adventurelog-frontend:{1}', env.REG, github.ref_name) || '' }}
